[versions]
detektVersion = "1.15.0"
androidAppCompatVersion = "1.6.1"
androidSocketIoVersion = "2.1.0"
gradleVersion = "8.2.2"
kotlinGradlePluginVersion = "1.9.10"
kotlinxSerializationVersion = "1.7.0"
mobileMultiplatformVersion = "0.14.2"
mokoSocketIoVersion = "0.6.0"
compileSdk = "34"
targetSdk = "34"
minSdk = "16"

[libraries]
appCompat = { module = "androidx.appcompat:appcompat", version.ref = "androidAppCompatVersion" }
detekt-gradle-plugin = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detektVersion" }
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradleVersion" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlinGradlePluginVersion" }
mobile-multiplatform = { module = "dev.icerock:mobile-multiplatform", version.ref = "mobileMultiplatformVersion" }
socketIo = { module = "io.socket:socket.io-client", version.ref = "androidSocketIoVersion" }
serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationVersion" }
mokoSocketIo = { module = "dev.icerock.moko:socket-io", version.ref = "mokoSocketIoVersion" }
detektFormatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detektVersion" }

